spring:
  datasource:
    url: jdbc:postgresql://turntable.proxy.rlwy.net:20162/railway
    username: postgres
    password: GYMbraeLdZMWZTyWfhswNsRQLpTPxWdo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8080
